// ---BALANCE -----//
export const ETHEREUM_BALANCE = "ETHEREUM_BALANCE"
export const LUMEN_BALANCE = "LUMEN_BALANCE"
export const NAIRA_BALANCE = "NAIRA_BALANCE"
export const RIPPLE_BALANCE = "RIPPLE_BALANCE"
export const BITCOIN_BALANCE = "BITCOIN_BALANCE"