// ---BALANCE -----//
export const ETHEREUM_BALANCE = "ETHEREUM_BALANCE"
export const LUMEN_BALANCE = "LUMEN_BALANCE"
export const NAIRA_BALANCE = "NAIRA_BALANCE"
export const RIPPLE_BALANCE = "RIPPLE_BALANCE"
export const BITCOIN_BALANCE = "BITCOIN_BALANCE"

export const GET_LIVE_PRICES = "GET_LIVE_PRICES"
export const GET_LIVE_CRYPTO_PRICES_USD = "GET_LIVE_CRYPTO_PRICES_USD"
export const GET_PAYTICA_USD_RATES = "GET_PAYTICA_USD_RATES"
export const GET_BALANCE_START = "GET_BALANCE_START"
export const GET_BALANCE_SUCCESS = "GET_BALANCE_SUCCESS"
export const GET_BALANCE_FAIL = "GET_BALANCE_START"
